<a href="https://colab.research.google.com/github/wesleyesantos/POSTECH/blob/main/Estat%C3%ADsticas_e_Algelin_em_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Métodos Matemáticos para DATA ANALYTICS





- álgebra linear  --> x + 2 = 5 - > x =3 (Resolver sistemas de equações lineares)
- x + y = 10 -> -3 + 13 =10 -------------(0,10), (2,8) -- infinitas sol. (diofantina)
- 2x - y =11

####Bibliotecas: Numpy, scipy, sympy


- Linguagem Katex

In [2]:
#Bibliotecas para trabalhar com números e símbolos númericos em geral
import numpy as np
import scipy as sc
import sympy as sy

In [10]:
#componentes principais: escalar, vetor e matriz
#Escalar é um número, considerado um tensor de ordem 0
#Vetor é necessidade de dois eixos

#Escalar
x = 2
#O x2 se tornou um vetor escalar
x2 = np.array([1,2,3])
#o x3 é uma matriz coluna, um vetor que possue 3 vetores com elementos escalares
x3 = np.array([[1],[2],[3]])
#np.matrix cria matriz, porém é mais usado array, Matriz tradicional
x4 = np.array([[1,2,3],[1,2,3],[1,2,3]])

#Matriz com 3 vetores (x,y,z) podem criar um objeto 3d por ter 3 dimensões (Altura, largura e profundidade)

In [11]:
#quase uma lista, diferencia-se de uma lista por não conter vírgulas
print(x2)
print()
print(x3)
print()
print(x4)

[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
import pandas as pd

In [16]:
lista = [1,2,3,4,5]

df = pd.DataFrame({'coluna 1': lista})

In [18]:
type(df)

pandas.core.frame.DataFrame

####Analogia de conceitos: Vetores e Matrizes

In [27]:
#Um array pode ser conhecido como um dataframe, no caso abaixo transformamos o caso anterior que era uma lista em array

#MATRIZ == DATAFRAME
#VETOR == SERIES

lista = np.array([1,2,3,4,5])

df = pd.DataFrame({'coluna': lista, 'coluna 2': lista})

In [31]:
type(df['coluna'])

pandas.core.series.Series

In [37]:
#acessa lista por elementos
#Vetor no caso abaixo pega o primeiro elemento vetor
#lista [:,1] #Não é possível fazer mais de uma seleção por se tratar de um array
lista[0] #primeiro elemento
lista[1] #segundo elemento
lista [:1] #pega do elemento 1 para traz

array([1])

In [39]:
x=3
y=2

print(2/3)

0.6666666666666666


####Soma

In [40]:
x2 + x3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [42]:
x3 + x4

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [43]:
x5 = np.array([[1],[2]])
#Não soma com outro array se não tiver o mesmo número de linhas ou de colunas

####Multiplicar

In [47]:
# multiplicar
# um vetor pode ser considerado uma matriz

# arr1 (x,y) / arr2 (z,w) ---> y = z / arr3 (x,w)

# dot produto interno entre matriz ou pode usar o @
# np.dot(x3, x4) --> retorna o erro ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0), devido uma coluna ter menos colunas do que a outra
# ao contrário funciona np.dot(x4, x3)
# A vezes B é diferente(!=) de B vezes A

x4@x3 #np.dot(x4, x3)

array([[14],
       [14],
       [14]])

####Divisão

##### Equação fundamental da álgebra linear

In [ ]:
# 2 .x = 4
# A.X = Y ---> Equação fundamental da álgebra linear

In [48]:
#1*0 = 0
#0*1 = 0
#O python informará que não existe divisão por zero
'''
Para os escalares:
O zero na soma e na subtração é o que chamamos de elemento neutro (ou seja não altera o resultado)
Na multiplicação e na divisão o 1 é o elemento neutro
'''

' \nPara os escalares:\nO zero na soma e na subtração é o que chamamos de elemento neutro (ou seja não altera o resultado)\nNa multiplicação e na divisão o 1 é o elemento neutro\n'

In [50]:
#criar uma matriz de zeros
zeros = np.zeros((3,3))

zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
#vetor
zeros = np.zeros(3)

zeros

array([0., 0., 0.])

In [ ]:
#Não passando como tupla o python não aceitará
zeros = np.zeros(3,1)

zeros

In [53]:
#Matriz de neutros
zeros = np.zeros((3,3))
ones = np.ones((3,3))
print(zeros)
print()
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Estrutura de uma matriz 3,3

$$A = \pmatrix{a_{00} & a_{01} & a_{02}\\ a_{10} & a_{11} & a_{12} \\ a_{20} & a_{21} & a_{22}}
$$

In [55]:
#Matriz identidade
id = np.eye(3)

id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
x4*id

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [58]:
#Matriz identidade basta pegar a matriz e multiplicar por 1

x4*1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Matriz identidade
--
$$ x . x^{-1} = 1$$

---

matriz inversa
--
$$ A . A^{-1} = I$$

---

Eq. fundamental da álgebra
--
só funciona se for uma matriz quafrada colunas iguais ao número de linhas equação 1 e 3
$$A . X = Y$$
$$A.A^{-1}.X = Y.A^{-1}$$
$$X = A^{-1}.Y $$

#Video 8